@server=http://localhost:3000
@userId=1b78d184-2f6f-47ef-b78a-a9d143b1d330




###
POST {{server}}/messages

###
POST {{server}}/messages
Authorization: {{userId}}
content-type: application/json

{
    "authorId": "222223",
    "authorName": "223333",
    "timestamp": "eee",
    "content" : "iere"

}


###
DELETE {{server}}/messages

###
GET {{server}}/messages

###
GET {{server}}/messages
Authorization: {{userId}}

###
GET {{server}}/user?id=1de00644-cc97-4103-9f5b-bc2d41756dda

###
PUT {{server}}/user
content-type: application/json

{
    "firstName": "222223",
    "lastName": "223333"

}


###
DELETE {{server}}/user


###
GET {{server}}/ida?parameter1=111

###
GET {{server}}/ida.nomnio?parameter1=123





###

DELETE {{server}}?parameter1=123

###
PUT {{server}}/ida?parameter1=123
